# Licensed Materials - Property of IBM
# IBM Order Management Software (5725-D10)
# (C) Copyright IBM Corp. 2018, 2021 All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
{{- if and .Values.global.license  .Values.global.licenseStoreCallCenter }}
{{- if eq .Values.omserver.healthMonitor.deploy true }}
{{- include "sch.config.init" (list . "om-chart.sch.chart.config.values") }}
{{- $sysOverridesInitPath := "/opt/ssfs/system_overrides.properties.init" }}
{{- $sysOverridesPath := "/opt/ssfs/runtime/properties/system_overrides.properties" }}
{{- $varServerStateDir := "/opt/ssfs/runtime/serverstate" }}
{{- $varServerStateJvmArg := (printf "%s=%s" "-Dserver.state.dir" $varServerStateDir) }}
{{- $readyProbePeriod := 15 }}
{{- $readyFailRestartSeconds := (mul .Values.omserver.common.readinessFailRestartAfterMinutes 60) | default 600 }}
{{- $readyFailThreshold := div $readyFailRestartSeconds $readyProbePeriod }}
{{- /* for agent liveness check is not appplicable hence hardcoding livenessProbeDelay */}}
{{- $liveProbeBeginDelaySecs := 60 }}
{{- $liveFailThreshold := add (div (sub $readyFailRestartSeconds $liveProbeBeginDelaySecs) $readyProbePeriod) 1 }}
{{- $custLabels := .Values.omserver.common.podLabels | default (dict) }}
{{- $stdPodLabel := "role" }}
{{- $stdPodLabelVal := "healthmonitor" }}
{{ $global := . }}
{{- $varTrustStoreJvmArg := "" }}
{{- $varTrustStorePath := "" }}
{{- $varTrustStorePass := "" }}
{{- $varTrustedDir := "" }}
{{- $varUseJDKTrustStore := "" }}
{{- $varKeyStoreJvmArg := "" }}
{{- $varKeyStorePath := "" }}

{{- if $global.Values.global.security }}
{{- if $global.Values.global.security.ssl }}
{{- if $global.Values.global.security.ssl.trustStore }}
  {{- if or ($global.Values.global.security.ssl.trustStore.trustJavaCACerts) (and ($global.Values.global.security.ssl.trustStore.trustedCertDir) (ne $global.Values.global.security.ssl.trustStore.trustedCertDir "")) (and ($global.Values.global.security.ssl.trustStore.storeLocation) (ne $global.Values.global.security.ssl.trustStore.storeLocation "")) }}
  {{- $varTrustStoreJvmArg = (printf "%s=%s %s=%s %s=%s" "-Djavax.net.ssl.trustStore" "$JAVA_TRUST_STORE_PATH" "-Djavax.net.ssl.trustStorePassword" "$JAVA_TRUST_STORE_PASS" "-Djavax.net.ssl.trustStoreType" "PKCS12") }}

  {{- if and $global.Values.global.security.ssl.trustStore.storeLocation (ne $global.Values.global.security.ssl.trustStore.storeLocation "") }} 
    {{- $varTrustStorePath = $global.Values.global.security.ssl.trustStore.storeLocation }}
  {{- else if and $global.Values.global.security.ssl.trustStore.trustedCertDir (ne $global.Values.global.security.ssl.trustStore.trustedCertDir "") }}
    {{- $varTrustStorePath = "/opt/ssfs/runtime/security/trustStore" }}
    {{- $varTrustStorePass = "changeit" }}
    {{- $varTrustedDir = $global.Values.global.security.ssl.trustStore.trustedCertDir }}
    {{- if $global.Values.global.security.ssl.trustStore.trustJavaCACerts }}
      {{- $varUseJDKTrustStore = "true" }}
    {{- end }}
  {{- else if $global.Values.global.security.ssl.trustStore.trustJavaCACerts }}
    {{- $varTrustStorePath = "/opt/ssfs/runtime/security/trustStore" }}
    {{- $varTrustStorePass = "changeit" }}
    {{- $varUseJDKTrustStore = "true" }}   
  {{- end }}

  {{- end }}
{{- end }}

{{- if $global.Values.global.security.ssl.keyStore }}
{{- if and $global.Values.global.security.ssl.keyStore.storeLocation (ne $global.Values.global.security.ssl.keyStore.storeLocation "")  }}
{{- $varKeyStoreJvmArg = (printf "%s=%s %s=%s %s=%s" "-Djavax.net.ssl.keyStore" "$JAVA_KEY_STORE_PATH" "-Djavax.net.ssl.keyStorePassword" "$JAVA_KEY_STORE_PASS" "-Djavax.net.ssl.keyStoreType" "PKCS12") }}
{{- $varKeyStorePath = $global.Values.global.security.ssl.keyStore.storeLocation }}  
{{- end }}
{{- end }}

{{- end }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "om-chart.fullname" . }}-healthmonitor
  labels:
{{ include "sch.metadata.labels.standard" (list .) | indent 4 }}
spec:
{{- if .Values.omserver.healthMonitor.replicaCount }}
  replicas: {{ .Values.omserver.healthMonitor.replicaCount | default 1 }}
{{- else }}
  replicas: {{ .Values.omserver.common.replicaCount | default 1 }}
{{- end }}
{{- if .Values.omserver.deploymentStrategy }}
  strategy: 
{{ toYaml .Values.omserver.deploymentStrategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
{{ include "sch.metadata.labels.standard" (list . "" (set $custLabels $stdPodLabel $stdPodLabelVal)) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "sch.metadata.labels.standard" (list . "" (set $custLabels $stdPodLabel $stdPodLabelVal)) | indent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering "" "" nil) | indent 8 }}
    spec:
{{- with .Values.omserver.common.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
{{- end }}
      affinity:
{{- include "om-chart.nodeAffinity" (list . .Values.omserver.common.nodeAffinity) | indent 8 }}
{{- include "om-chart.podAffinity" (list . .Values.omserver.common.podAffinity) | indent 8 }}
{{- include "om-chart.podAntiAffinity" (list . .Values.omserver.common.podAntiAffinity $stdPodLabel $stdPodLabelVal) | indent 8 }}
      serviceAccountName: {{ .Values.global.serviceAccountName | default "default" }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: {{ .Values.global.persistence.securityContext.fsGroup | default 0 }}
        supplementalGroups: [{{ .Values.global.persistence.securityContext.supplementalGroup | default 0 }}]
      {{- if eq (include "om-chart.require-datasetup" .) "true" }}
      initContainers:
      - name: {{ template "om-chart.fullname" . }}-healthmonitor-init
        {{- if and .Values.omserver.image.name .Values.omserver.image.tag }}
        image: "{{ .Values.global.image.repository }}/{{ .Values.omserver.image.name }}:{{ .Values.omserver.image.tag }}"
        {{- else }}
        image: "{{ .Values.global.image.repository }}/{{ .Values.global.image.agentName }}:{{ .Values.global.image.tag }}"
        {{- end }}
        securityContext:
          privileged: false
          runAsUser: 1000
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        command: ['/bin/bash', '-c']
        args:
        - 'while [ -z $(find /mediator -maxdepth 1 -name datasetup.complete) ]; do echo "datasetup not complete $(date +%Y-%m-%d.%H.%M.%S)"; sleep 30; done; echo "datasetup found complete $(date +%Y-%m-%d.%H.%M.%S)"'
        volumeMounts:
        - name: {{ .Values.global.persistence.claims.name }}
          mountPath: "/shared"
        - name: mediator
          mountPath: "/mediator"
      {{- end }}
      containers:
      - name: {{ template "om-chart.fullname" . }}-healthmonitor
        {{- if and .Values.omserver.image.name .Values.omserver.image.tag }}
        image: "{{ .Values.global.image.repository }}/{{ .Values.omserver.image.name }}:{{ .Values.omserver.image.tag }}"
        {{- else }}
        image: "{{ .Values.global.image.repository }}/{{ .Values.global.image.agentName }}:{{ .Values.global.image.tag }}"
        {{- end }}
        imagePullPolicy: {{ .Values.omserver.image.pullPolicy }}
        env:
        {{- if ne $varTrustStorePath "" }}
        - name: JAVA_TRUST_STORE_PATH
          value: {{ $varTrustStorePath | quote }}
        - name: JAVA_TRUST_STORE_PASS
          {{- if ne $varTrustStorePass "" }}
          value: {{ $varTrustStorePass | quote }}
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ $global.Values.global.appSecret }}
              key: trustStorePassword
          {{- end }}
        {{- end }} 
        {{- if ne $varUseJDKTrustStore "" }}
        - name: USE_JDK_TRUST_STORE
          value: {{ $varUseJDKTrustStore | quote }}            
        {{- end }}        
        {{- if ne $varTrustedDir "" }}
        - name: OMS_TRUSTED_CERTS_DIR
          value: {{ $varTrustedDir | quote }}            
        {{- end }} 

       {{- if ne $varKeyStorePath "" }}
        - name: JAVA_KEY_STORE_PATH
          value: {{ $varKeyStorePath | quote }}
        - name: JAVA_KEY_STORE_PASS
          valueFrom:
            secretKeyRef:
              name: {{ $global.Values.global.appSecret }}
              key: keyStorePassword            
       {{- end }}
        - name: OM_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OM_RELEASE
          value: {{ .Release.Name }}
        - name: dbpassword
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.appSecret }}
              key: dbpassword
        - name: LOG_FORMAT
          value: {{ .Values.global.log.format | default "json" }}
{{- with .Values.global.envs }}
{{ toYaml . | indent 8 }}
{{- end }}
        resources:
{{- if .Values.omserver.healthMonitor.resources }}
{{ toYaml .Values.omserver.healthMonitor.resources | indent 10 }}
{{- else }}
{{ toYaml .Values.omserver.common.resources | indent 10 }}
{{- end }}
        securityContext:
          privileged: false
          runAsUser: 1000
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        command: ["/bin/bash", "-c"]
        {{- $commonArg := printf "%s %s %s %s" "/opt/ssfs/runtime/container-scripts/utils/evaluateEnvs.sh" $sysOverridesInitPath $sysOverridesPath "&& /opt/ssfs/runtime/container-scripts/utils/configCerts.sh && "}}
        {{- if .Values.omserver.healthMonitor.jvmArgs }}
        args:
        - '{{ $commonArg }} 
        /opt/ssfs/runtime/bin/startHealthMonitor.sh -jvmargs {{ printf "%s %s %s %s" (cat .Values.omserver.common.jvmArgs .Values.omserver.healthMonitor.jvmArgs ) $varServerStateJvmArg $varTrustStoreJvmArg $varKeyStoreJvmArg | quote }}'
        {{- else if .Values.omserver.common.jvmArgs }}
        args:
        - '{{ $commonArg }} 
        /opt/ssfs/runtime/bin/startHealthMonitor.sh -jvmargs {{ printf "%s %s %s %s" .Values.omserver.common.jvmArgs $varServerStateJvmArg $varTrustStoreJvmArg $varKeyStoreJvmArg | quote }}'
	      {{- else }}
        args:
        - '{{ $commonArg }} 
        /opt/ssfs/runtime/bin/startHealthMonitor.sh -jvmargs {{ printf "%s %s %s" $varServerStateJvmArg $varTrustStoreJvmArg $varKeyStoreJvmArg | quote }}'
        {{- end }}
        livenessProbe:
          exec:
            command:
            - '/bin/bash'
            - '-c'
            - '/opt/ssfs/runtime/container-scripts/utils/agentStartupTest.sh {{ $varServerStateDir }} {{ printf "%s--%s_*" "HealthMonitor" "HealthMonitor" | quote }} {{ div $readyFailRestartSeconds 60 }}'
          initialDelaySeconds: {{ $liveProbeBeginDelaySecs }}
          {{- /* check for liveness every n seconds */}}
          periodSeconds: {{ $readyProbePeriod }}
          {{- /* A successful probe must return in less than 1 seconds */}}
          timeoutSeconds: 1
          failureThreshold: {{ $liveFailThreshold }}
        readinessProbe:
          exec:
            command:
            - '/bin/bash'
            - '-c'
            - '/opt/ssfs/runtime/container-scripts/utils/agentStartupTest.sh {{ $varServerStateDir }} {{ printf "%s--%s_*" "HealthMonitor" "HealthMonitor" | quote }} {{ div $readyFailRestartSeconds 60 }}'
          initialDelaySeconds: 1
          {{- /* check for readiness every n seconds */}}
          periodSeconds: {{ $readyProbePeriod }}
          {{- /* A successful probe must return in less than 1 seconds */}}
          timeoutSeconds: 1
          failureThreshold: {{ $readyFailThreshold }}
        workingDir: "/opt/ssfs/runtime/"
        volumeMounts:
        - name: {{ .Values.global.persistence.claims.name }}
          mountPath: "/shared"
        - name: config
          mountPath: "{{ $sysOverridesInitPath }}"
          subPath: system_overrides.properties
        {{- if .Values.global.customerOverrides }}
        - name: config
          mountPath: "/opt/ssfs/runtime/properties/customer_overrides.properties"
          subPath: customer_overrides.properties
        {{- end }}
        {{- /* mount custom config maps */ -}}
        {{- if .Values.global.customConfigMaps -}}
        {{ range .Values.global.customConfigMaps -}}
        {{ if . -}}
        {{ $configMap := . }}
        {{- if and $configMap.name $configMap.mountPath }}
        - name: {{ $configMap.name }}
          mountPath: {{ $configMap.mountPath }}
          {{- if $configMap.subPath }}
          subPath: {{ $configMap.subPath }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- /* mount custom secrets */ -}}
        {{- if .Values.global.customSecrets -}}
        {{ range .Values.global.customSecrets -}}
        {{ if . -}}
        {{ $secret := . }}
        {{- if and $secret.name $secret.mountPath }}
        - name: {{ $secret.name }}
          mountPath: {{ $secret.mountPath }}
          {{- if $secret.readOnly }}
          readOnly: {{ $secret.readOnly }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        # - name: host-timezone
        #   mountPath: /etc/localtime
      volumes:
      - name: config
        configMap:
          name: {{ template "om-chart.fullname" . }}-config
          items:
        {{- if .Values.global.customerOverrides }}
          - key: customer_overrides.properties
            path: customer_overrides.properties
        {{- end }}
          - key: system_overrides.properties
            path: system_overrides.properties
      - name: secret
        secret:
          secretName: {{ .Values.global.appSecret }}
      - name: {{ .Values.global.persistence.claims.name }}
        persistentVolumeClaim:
          claimName: {{ template "om-chart.fullname" . }}-{{ .Values.global.persistence.claims.name | lower }}
      - name: mediator
        configMap:
          name: {{ template "om-chart.fullname" . }}-mediator
      {{- /* custom config maps */ -}}
      {{- if .Values.global.customConfigMaps -}}
      {{ range .Values.global.customConfigMaps -}}
      {{ if . -}}
      {{ $configMap := . }}
      {{- if and $configMap.name $configMap.mountPath }}
      - name: {{ $configMap.name }}
        configMap:
          name: {{ $configMap.name }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- /* custom secrets */ -}}
      {{- if .Values.global.customSecrets -}}
      {{ range .Values.global.customSecrets -}}
      {{ if . -}}
      {{ $secret := . }}
      {{- if and $secret.name $secret.mountPath }}
      - name: {{ $secret.name }}
        secret:
          secretName: {{ $secret.name }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      # - name: host-timezone
      #   hostPath:
      #     path: /etc/localtime
{{- end }}
{{- end }}