kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oms-rolebinding-<namespace>
  namespace: <namespace>
subjects:
  - kind: ServiceAccount
    name: ibm-oms-ent-prod-ibm-oms-ent-prod
    namespace: <namespace>
roleRef:
  kind: Role
  name: oms-role-<namespace>
  apiGroup: rbac.authorization.k8s.io