kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oms-rolebinding-gitops-cp-sterling-oms
  namespace: oms-role-gitops-cp-sterling-oms
subjects:
  - kind: ServiceAccount
    name: ibm-oms-ent-prod-ibm-oms-ent-prod
    namespace: gitops-cp-sterling-oms
roleRef:
  kind: Role
  name: oms-role-gitops-cp-sterling-oms
  apiGroup: rbac.authorization.k8s.io