kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oms-role-gitops-cp-sterling-oms
  namespace: gitops-cp-sterling-oms
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'watch', 'list', 'create', 'delete', 'patch', 'update']

